providers = ["node"]

[variables]
NODE_VERSION = "18"

[phases.setup]
nixPkgs = ["nodejs_18", "npm"]

[phases.install]
cmds = ["cd payload && npm install"]

[phases.build]
cmds = ["cd payload && npm run build"]

[start]
cmd = "cd payload && npm start"