[build]
builder = "nixpacks"
buildCommand = "cd payload && npm install && npm run build"

[deploy]
startCommand = "cd payload && npm run start"
healthcheckPath = "/"
healthcheckTimeout = 100
restartPolicyType = "on_failure"